sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t nachathu2014/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nachathu2014/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-056341410405"
  bucket_path: "docker-react"
  on:
    branch: master
  

